package com.vicationfly.app;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import android.text.*;import java.util.*;
public class MainActivity extends Activity{
 final int ORANGE=Color.rgb(255,102,0),DARK=Color.rgb(25,29,37),CREAM=Color.rgb(250,247,242),MUTED=Color.rgb(112,116,124),LINE=Color.rgb(232,228,221);
 LinearLayout body,searchCard,results;EditText from,to;TextView dep,ret,cabin,travellers;boolean round=true;String depDate="",retDate="";ArrayList<String[]> airports=new ArrayList<>();Random random=new Random();
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(CREAM);getWindow().setNavigationBarColor(Color.WHITE);seed();splash();}
 TextView text(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
 GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 GradientDrawable border(int c,int s,float r){GradientDrawable g=bg(c,r);g.setStroke(1,s);return g;}
 LinearLayout box(int c,float r){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackground(bg(c,r));return x;}
 LinearLayout.LayoutParams p(int w,int h,float f){return new LinearLayout.LayoutParams(w,h,f);}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(ORANGE,20));return b;}
 Button outline(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(DARK);b.setBackground(border(Color.WHITE,LINE,18));return b;}
 Space gap(int h){Space s=new Space(this);s.setLayoutParams(p(1,h,0));return s;}
 void splash(){FrameLayout f=new FrameLayout(this);f.setBackgroundColor(CREAM);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(17);TextView logo=text("▣✈",54,ORANGE);logo.setGravity(17);TextView n=text("Vicationfly",36,DARK);n.setGravity(17);n.setTypeface(Typeface.DEFAULT,1);TextView q=text("Find your next flight.",16,MUTED);q.setGravity(17);c.addView(logo);c.addView(n);c.addView(q);f.addView(c,new FrameLayout.LayoutParams(-1,-1));TextView plane=text("✈",25,ORANGE);FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(60,50);pp.gravity=Gravity.BOTTOM;pp.leftMargin=-60;pp.bottomMargin=80;f.addView(plane,pp);setContentView(f);plane.animate().translationX(getResources().getDisplayMetrics().widthPixels+80).setDuration(1300).withEndAction(()->{plane.setTranslationX(-60);plane.animate().translationX(getResources().getDisplayMetrics().widthPixels+80).setDuration(1300).start();});f.postDelayed(this::home,1700);}
 void home(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CREAM);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(20,18,20,25);
 TextView h=text("Vicationfly",30,DARK);h.setTypeface(Typeface.DEFAULT,1);body.addView(h,p(-1,52,0));body.addView(text("Plan your next journey",16,MUTED),p(-1,30,0));body.addView(gap(12));buildSearch();body.addView(searchCard,p(-1,-2,0));body.addView(gap(18));
 LinearLayout feature=box(DARK,25);feature.setPadding(20,18,20,18);TextView ft=text("Travel, beautifully.",21,Color.WHITE);ft.setTypeface(Typeface.DEFAULT,1);feature.addView(ft);feature.addView(text("Search airlines and booking partners through one clean experience.",14,0xffd8dce3));body.addView(feature,p(-1,-2,0));body.addView(gap(15));
 body.addView(text("Vicationfly is a flight search and booking intermediary. Availability and prices are supplied by airlines and booking partners and may change until booking is confirmed.",11,MUTED));
 sv.addView(body);root.addView(sv,p(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setGravity(17);nav.setBackgroundColor(Color.WHITE);String[]n={"⌂\nHome","⌕\nSearch","▣\nMy Trips","◉\nProfile"};for(String s:n){TextView v=text(s,12,DARK);v.setGravity(17);nav.addView(v,p(0,70,1));}root.addView(nav,p(-1,70,0));setContentView(root);}
 void buildSearch(){searchCard=box(Color.WHITE,28);searchCard.setPadding(18,18,18,18);LinearLayout tabs=new LinearLayout(this);tabs.setGravity(Gravity.CENTER_VERTICAL);TextView rt=text("ROUND TRIP",12,ORANGE);rt.setTypeface(Typeface.DEFAULT,1);tabs.addView(rt,p(0,40,1));Button one=outline("One way");one.setOnClickListener(v->{round=!round;one.setText(round?"One way":"Round trip");rt.setText(round?"ROUND TRIP":"ONE WAY");});tabs.addView(one,p(105,42,0));searchCard.addView(tabs);searchCard.addView(gap(10));
 searchCard.addView(text("FROM",10,ORANGE));from=field("Airport, city or code");searchCard.addView(from,p(-1,58,0));searchCard.addView(gap(8));searchCard.addView(text("TO",10,ORANGE));to=field("Airport, city or code");searchCard.addView(to,p(-1,58,0));searchCard.addView(gap(10));
 LinearLayout dates=new LinearLayout(this);LinearLayout a=choice("DEPARTURE");dep=text("Select date",15,DARK);a.addView(dep);a.setOnClickListener(v->date(false));dates.addView(a,p(0,70,1));dates.addView(gap(8),p(8,1,0));LinearLayout b=choice("RETURN");ret=text("Select date",15,DARK);b.addView(ret);b.setOnClickListener(v->{if(round)date(true);});dates.addView(b,p(0,70,1));searchCard.addView(dates);searchCard.addView(gap(9));
 LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);travellers=text("1 adult",14,DARK);row.addView(travellers,p(0,46,1));Button people=outline("Travellers");people.setOnClickListener(v->travellersDialog());row.addView(people,p(112,44,0));searchCard.addView(row);searchCard.addView(gap(7));cabin=text("Economy",14,DARK);cabin.setGravity(Gravity.CENTER_VERTICAL);cabin.setPadding(16,0,16,0);cabin.setBackground(border(0xfff7f4ef,LINE,16));cabin.setOnClickListener(v->cabinDialog());searchCard.addView(cabin,p(-1,48,0));searchCard.addView(gap(13));Button go=btn("Search flights");go.setTextSize(17);go.setOnClickListener(v->search());searchCard.addView(go,p(-1,58,0));}
 LinearLayout choice(String s){LinearLayout x=box(0xfff7f4ef,17);x.setPadding(12,7,12,4);TextView l=text(s,9,ORANGE);l.setTypeface(Typeface.DEFAULT,1);x.addView(l);return x;}
 EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine();e.setTextSize(16);e.setTextColor(DARK);e.setHintTextColor(0xff999ba1);e.setPadding(16,0,16,0);e.setBackground(border(0xfff7f4ef,LINE,17));e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){suggest(e,s.toString());}});return e;}
 void suggest(EditText e,String q){ViewGroup par=(ViewGroup)e.getParent();int i=par.indexOfChild(e);if(i+1<par.getChildCount()&&"drop".equals(par.getChildAt(i+1).getTag()))par.removeViewAt(i+1);if(q.trim().isEmpty())return;ArrayList<String[]>m=new ArrayList<>();String z=q.toLowerCase(Locale.US);for(String[]a:airports)if((a[0]+" "+a[1]+" "+a[2]+" "+a[3]).toLowerCase(Locale.US).contains(z))m.add(a);Collections.shuffle(m,random);int n=Math.min(5,m.size());if(n==0)return;LinearLayout d=box(Color.WHITE,18);d.setTag("drop");d.setPadding(5,5,5,5);d.setElevation(16);for(int k=0;k<n;k++){String[]a=m.get(k);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView dot=text("●",11,ORANGE);r.addView(dot,p(28,54,0));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.addView(text(a[0],15,DARK));info.addView(text(a[1]+"  •  "+a[2]+"  •  "+a[3],11,MUTED));r.addView(info,p(0,54,1));final String value=a[0]+" ("+a[2]+")";r.setOnClickListener(v->{e.setText(value);e.setSelection(value.length());d.setVisibility(View.GONE);});d.addView(r,p(-1,54,0));}par.addView(d,i+1,p(-1,-2,0));}
 void date(boolean returning){Calendar c=Calendar.getInstance();DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{String x=String.format(Locale.US,"%02d/%02d/%04d",day,m+1,y);if(returning){retDate=x;ret.setText(x);}else{depDate=x;dep.setText(x);if(round)date(true);}},c.get(1),c.get(2),c.get(5));d.setTitle(returning?"Return date":"Departure date");d.show();}
 void travellersDialog(){new AlertDialog.Builder(this).setTitle("Travellers").setItems(new String[]{"1 adult","2 adults","3 adults","4 adults","2 adults • 1 child","2 adults • 1 infant"},(d,w)->travellers.setText(new String[]{"1 adult","2 adults","3 adults","4 adults","2 adults • 1 child","2 adults • 1 infant"}[w])).show();}
 void cabinDialog(){String[]x={"Economy","Premium Economy","Business","First"};new AlertDialog.Builder(this).setTitle("Cabin class").setSingleChoiceItems(x,Arrays.asList(x).indexOf(cabin.getText().toString()),(d,w)->{cabin.setText(x[w]);d.dismiss();}).show();}
 void search(){if(from.getText().toString().trim().isEmpty()||to.getText().toString().trim().isEmpty()){toast("Choose From and To.");return;}if(depDate.isEmpty()||(round&&retDate.isEmpty())){toast("Choose both travel dates.");return;}((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(from.getWindowToken(),0);searchCard.animate().translationY(-30).alpha(.12f).setDuration(300).withEndAction(()->{searchCard.setVisibility(View.GONE);showResults();}).start();}
 void showResults(){results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);results.setPadding(0,4,0,20);body.addView(results,p(-1,-2,0));results.setAlpha(0);results.animate().alpha(1).setDuration(450).start();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView h=text("Flight results",26,DARK);h.setTypeface(Typeface.DEFAULT,1);top.addView(h,p(0,55,1));Button f=outline("Filters");f.setOnClickListener(v->filterDialog());top.addView(f,p(95,44,0));results.addView(top);LinearLayout route=box(0xffffeee3,18);route.setPadding(15,12,15,12);route.addView(text(from.getText()+"  →  "+to.getText(),16,DARK));route.addView(text(depDate+(round?"  •  "+retDate:"")+"  •  "+cabin.getText(),12,MUTED));results.addView(route,p(-1,-2,0));results.addView(gap(12));
 LinearLayout empty=box(Color.WHITE,25);empty.setGravity(17);empty.setPadding(24,32,24,32);TextView plane=text("✈",48,ORANGE);plane.setGravity(17);empty.addView(plane);TextView title=text("Live search connected by architecture",21,DARK);title.setGravity(17);title.setTypeface(Typeface.DEFAULT,1);empty.addView(title);TextView msg=text("This build never invents flights or prices. Connect a real Flight API through the Vicationfly backend to populate live results.",14,MUTED);msg.setGravity(17);empty.addView(msg);Button retry=outline("Try live search");retry.setOnClickListener(v->toast("No real provider credentials are configured in this APK."));empty.addView(retry,p(-1,52,0));results.addView(empty,p(-1,-2,0));results.addView(gap(12));TextView note=text("Before booking, Vicationfly must revalidate availability and price with the provider.",11,MUTED);results.addView(note);Button back=outline("New search");back.setOnClickListener(v->{results.setVisibility(View.GONE);searchCard.setVisibility(View.VISIBLE);searchCard.setAlpha(1);searchCard.setTranslationY(0);});results.addView(back,p(-1,54,0));}
 void filterDialog(){String[]x={"Cheapest","Fastest","Best","Non-stop","1 stop or fewer","Morning departure","Evening departure"};new AlertDialog.Builder(this).setTitle("Filters & sorting").setMultiChoiceItems(x,null,null).setPositiveButton("Apply",null).setNegativeButton("Cancel",null).show();}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 void seed(){String[][]x={{"Tel Aviv","Ben Gurion Airport","TLV","Israel"},{"London","Heathrow Airport","LHR","United Kingdom"},{"Paris","Charles de Gaulle","CDG","France"},{"New York","John F. Kennedy","JFK","United States"},{"Dubai","Dubai International","DXB","UAE"},{"Amsterdam","Schiphol","AMS","Netherlands"},{"Athens","International","ATH","Greece"},{"Frankfurt","Airport","FRA","Germany"},{"Rome","Fiumicino","FCO","Italy"},{"Madrid","Barajas","MAD","Spain"},{"Barcelona","El Prat","BCN","Spain"},{"Istanbul","Istanbul Airport","IST","Türkiye"},{"Doha","Hamad International","DOH","Qatar"},{"Singapore","Changi","SIN","Singapore"},{"Tokyo","Haneda","HND","Japan"},{"Seoul","Incheon","ICN","South Korea"},{"Toronto","Pearson","YYZ","Canada"},{"Los Angeles","LAX","LAX","United States"},{"San Francisco","SFO","SFO","United States"},{"Bangkok","Suvarnabhumi","BKK","Thailand"},{"Manila","Ninoy Aquino","MNL","Philippines"},{"Sydney","Kingsford Smith","SYD","Australia"},{"Mumbai","Chhatrapati Shivaji","BOM","India"},{"Delhi","Indira Gandhi","DEL","India"},{"Vienna","International","VIE","Austria"},{"Zurich","Airport","ZRH","Switzerland"},{"Lisbon","Humberto Delgado","LIS","Portugal"},{"Copenhagen","Airport","CPH","Denmark"},{"Oslo","Gardermoen","OSL","Norway"},{"Stockholm","Arlanda","ARN","Sweden"}};airports.addAll(Arrays.asList(x));}
}